services:
  tmc-dlt:
    build:
      context: .
      dockerfile: ./devops/Dockerfile.dlt
    env_file:
      - test.env
    environment:
      - DEBUG_LOG=true
      - LOCAL=true
    volumes:
      - ./service_accounts:/app/service_accounts

  tmc-trino:
    build:
      context: .
      dockerfile: ./devops/Dockerfile.trino
    env_file:
      - trino.env
    environment:
      - DEBUG_LOG=true
      - LOCAL=true
