services:
  tmc-dlt:
    build:
      context: .
      dockerfile: ./devops/Dockerfile.dlt
    env_file:
      - test.env
    environment:
      - DEBUG_LOG=true
      - LOCAL=true
    volumes:
      - ./service_accounts:/app/service_accounts

  tmc-sling:
    platform: "linux/amd64"
    build:
      context: .
      dockerfile: ./devops/Dockerfile.sling
    environment:
      - DEBUG_LOG=true
      - LOCAL=true
    volumes:
      - ./src/sling:/app/src
      - ./service_accounts:/app/service_accounts
